# Form implementation generated from reading ui file '.\simple_emailer.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormSimpleEmailer(object):
    def setupUi(self, FormSimpleEmailer):
        FormSimpleEmailer.setObjectName("FormSimpleEmailer")
        FormSimpleEmailer.resize(532, 631)
        self.list_widget_emails_list = QtWidgets.QListWidget(parent=FormSimpleEmailer)
        self.list_widget_emails_list.setGeometry(QtCore.QRect(10, 30, 261, 231))
        self.list_widget_emails_list.setObjectName("list_widget_emails_list")
        self.label_emails_list = QtWidgets.QLabel(parent=FormSimpleEmailer)
        self.label_emails_list.setGeometry(QtCore.QRect(10, 10, 261, 16))
        self.label_emails_list.setObjectName("label_emails_list")
        self.label_sender_email = QtWidgets.QLabel(parent=FormSimpleEmailer)
        self.label_sender_email.setGeometry(QtCore.QRect(280, 10, 241, 16))
        self.label_sender_email.setObjectName("label_sender_email")
        self.line_edit_sender_email = QtWidgets.QLineEdit(parent=FormSimpleEmailer)
        self.line_edit_sender_email.setGeometry(QtCore.QRect(280, 30, 241, 20))
        self.line_edit_sender_email.setObjectName("line_edit_sender_email")
        self.label_sender_password = QtWidgets.QLabel(parent=FormSimpleEmailer)
        self.label_sender_password.setGeometry(QtCore.QRect(280, 60, 241, 16))
        self.label_sender_password.setObjectName("label_sender_password")
        self.line_edit_sender_password = QtWidgets.QLineEdit(parent=FormSimpleEmailer)
        self.line_edit_sender_password.setGeometry(QtCore.QRect(280, 80, 241, 20))
        self.line_edit_sender_password.setObjectName("line_edit_sender_password")
        self.label_recipient_email = QtWidgets.QLabel(parent=FormSimpleEmailer)
        self.label_recipient_email.setGeometry(QtCore.QRect(280, 160, 241, 16))
        self.label_recipient_email.setObjectName("label_recipient_email")
        self.line_edit_recipient_email = QtWidgets.QLineEdit(parent=FormSimpleEmailer)
        self.line_edit_recipient_email.setGeometry(QtCore.QRect(280, 180, 241, 20))
        self.line_edit_recipient_email.setObjectName("line_edit_recipient_email")
        self.combo_box_email_type = QtWidgets.QComboBox(parent=FormSimpleEmailer)
        self.combo_box_email_type.setGeometry(QtCore.QRect(280, 240, 241, 22))
        self.combo_box_email_type.setObjectName("combo_box_email_type")
        self.label_email_type = QtWidgets.QLabel(parent=FormSimpleEmailer)
        self.label_email_type.setGeometry(QtCore.QRect(280, 220, 241, 16))
        self.label_email_type.setObjectName("label_email_type")
        self.label_email_text = QtWidgets.QLabel(parent=FormSimpleEmailer)
        self.label_email_text.setGeometry(QtCore.QRect(10, 320, 511, 16))
        self.label_email_text.setObjectName("label_email_text")
        self.text_edit_email_text = QtWidgets.QPlainTextEdit(parent=FormSimpleEmailer)
        self.text_edit_email_text.setGeometry(QtCore.QRect(10, 340, 511, 241))
        self.text_edit_email_text.setObjectName("text_edit_email_text")
        self.button_send_email = QtWidgets.QPushButton(parent=FormSimpleEmailer)
        self.button_send_email.setGeometry(QtCore.QRect(10, 590, 111, 31))
        self.button_send_email.setObjectName("button_send_email")
        self.button_exit = QtWidgets.QPushButton(parent=FormSimpleEmailer)
        self.button_exit.setGeometry(QtCore.QRect(410, 590, 111, 31))
        self.button_exit.setObjectName("button_exit")
        self.button_about = QtWidgets.QPushButton(parent=FormSimpleEmailer)
        self.button_about.setGeometry(QtCore.QRect(290, 590, 111, 31))
        self.button_about.setObjectName("button_about")
        self.label_email_subject = QtWidgets.QLabel(parent=FormSimpleEmailer)
        self.label_email_subject.setGeometry(QtCore.QRect(10, 270, 511, 16))
        self.label_email_subject.setObjectName("label_email_subject")
        self.line_edit_email_subject = QtWidgets.QLineEdit(parent=FormSimpleEmailer)
        self.line_edit_email_subject.setGeometry(QtCore.QRect(10, 290, 511, 20))
        self.line_edit_email_subject.setObjectName("line_edit_email_subject")
        self.check_box_use_env_variables = QtWidgets.QCheckBox(parent=FormSimpleEmailer)
        self.check_box_use_env_variables.setGeometry(QtCore.QRect(280, 110, 241, 31))
        self.check_box_use_env_variables.setObjectName("check_box_use_env_variables")

        self.retranslateUi(FormSimpleEmailer)
        QtCore.QMetaObject.connectSlotsByName(FormSimpleEmailer)

    def retranslateUi(self, FormSimpleEmailer):
        _translate = QtCore.QCoreApplication.translate
        FormSimpleEmailer.setWindowTitle(_translate("FormSimpleEmailer", "Simple Emailer GUI"))
        self.label_emails_list.setText(_translate("FormSimpleEmailer", "Список писем"))
        self.label_sender_email.setText(_translate("FormSimpleEmailer", "Почта"))
        self.label_sender_password.setText(_translate("FormSimpleEmailer", "Пароль"))
        self.label_recipient_email.setText(_translate("FormSimpleEmailer", "Получатель письма"))
        self.label_email_type.setText(_translate("FormSimpleEmailer", "Тип текста письма"))
        self.label_email_text.setText(_translate("FormSimpleEmailer", "Текст письма"))
        self.button_send_email.setText(_translate("FormSimpleEmailer", "Отправить"))
        self.button_exit.setText(_translate("FormSimpleEmailer", "Выйти"))
        self.button_about.setText(_translate("FormSimpleEmailer", "О программе"))
        self.label_email_subject.setText(_translate("FormSimpleEmailer", "Заголовок письма"))
        self.check_box_use_env_variables.setText(_translate("FormSimpleEmailer", "Взять почту и пароль из переменных\n"
"окружения"))
