# Form implementation generated from reading ui file '.\simple_emailer_about.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormSimpleEmailerAbout(object):
    def setupUi(self, FormSimpleEmailerAbout):
        FormSimpleEmailerAbout.setObjectName("FormSimpleEmailerAbout")
        FormSimpleEmailerAbout.resize(492, 233)
        font = QtGui.QFont()
        font.setPointSize(8)
        FormSimpleEmailerAbout.setFont(font)
        self.label_icon = QtWidgets.QLabel(parent=FormSimpleEmailerAbout)
        self.label_icon.setGeometry(QtCore.QRect(30, 30, 91, 91))
        self.label_icon.setText("")
        self.label_icon.setObjectName("label_icon")
        self.label_simple_emailer_desktop = QtWidgets.QLabel(parent=FormSimpleEmailerAbout)
        self.label_simple_emailer_desktop.setGeometry(QtCore.QRect(160, 20, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_simple_emailer_desktop.setFont(font)
        self.label_simple_emailer_desktop.setObjectName("label_simple_emailer_desktop")
        self.label_version = QtWidgets.QLabel(parent=FormSimpleEmailerAbout)
        self.label_version.setGeometry(QtCore.QRect(160, 80, 321, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_version.setFont(font)
        self.label_version.setObjectName("label_version")
        self.label_description = QtWidgets.QLabel(parent=FormSimpleEmailerAbout)
        self.label_description.setGeometry(QtCore.QRect(160, 110, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_description.setFont(font)
        self.label_description.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_description.setObjectName("label_description")
        self.button_close = QtWidgets.QPushButton(parent=FormSimpleEmailerAbout)
        self.button_close.setGeometry(QtCore.QRect(360, 190, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.button_close.setFont(font)
        self.button_close.setObjectName("button_close")
        self.label_git = QtWidgets.QLabel(parent=FormSimpleEmailerAbout)
        self.label_git.setGeometry(QtCore.QRect(10, 200, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_git.setFont(font)
        self.label_git.setObjectName("label_git")

        self.retranslateUi(FormSimpleEmailerAbout)
        QtCore.QMetaObject.connectSlotsByName(FormSimpleEmailerAbout)

    def retranslateUi(self, FormSimpleEmailerAbout):
        _translate = QtCore.QCoreApplication.translate
        FormSimpleEmailerAbout.setWindowTitle(_translate("FormSimpleEmailerAbout", "О приложении"))
        self.label_simple_emailer_desktop.setText(_translate("FormSimpleEmailerAbout", "Simple Emailer Desktop"))
        self.label_version.setText(_translate("FormSimpleEmailerAbout", "Версия: 0.1.0"))
        self.label_description.setText(_translate("FormSimpleEmailerAbout", "Simple Emailer Desktop - утилита для отправки писем\n"
"через SMTP Gmail."))
        self.button_close.setText(_translate("FormSimpleEmailerAbout", "Закрыть"))
        self.label_git.setText(_translate("FormSimpleEmailerAbout", "GitHub: github.com/Shuwiku/simple_emailer_desktop.git"))
